import courses from '../../../../courses.json';

const Statistics_Major_Requirements = [
    {
      "Division": "Lower Divsion",
      "Requirement": "Calculus I",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses['MATH 1A']]
    },
    {
        "Division": "Lower Divsion",
        "Requirement": "Calculus II",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['MATH 1B']]
      },
      {
        "Division": "Lower Divsion",
        "Requirement": "Multivariable Calculus",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['MATH 53']]
      },
      {
        "Division": "Lower Divsion",
        "Requirement": "Linear Algebra & Differential Equations",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['MATH 1A']]
      },
      {
        "Division": "Lower Divsion",
        "Requirement": "Foundational Statistics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['COMPSCI C8'], courses['STAT 20'], courses['STAT 28']]
      },
      {
        "Division": "Upper Divsion",
        "Requirement": "Probability",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['STAT 134'], courses['STAT 140']]
      },
      {
        "Division": "Upper Divsion",
        "Requirement": "Concepts of Statistics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['STAT 135']]
      },
      {
        "Division": "Upper Divsion",
        "Requirement": "Concepts in Computing with Data",
        "Number of Classes": 1,
        "Minimum Units": 3,
        "Course": [courses['STAT 133']]
      },
      {
        "Division": "Upper Divsion",
        "Requirement": "Statistics Electives",
        "Number of Classes": 3,
        "Minimum Units": 10,
        "Course": [courses['STAT 150'], courses['STAT 151A'], courses['STAT 152'], courses['STAT 153'], courses['STAT 154'], courses['STAT 155'], courses['STAT 157'], courses['STAT 158'], courses['STAT 159']]
      },
      {
        "Division": "Upper Divsion",
        "Requirement": "Applied Cluster Courses",
        "Number of Classes": 3,
        "Minimum Units": 9,
        "Course": ['departmentsubgroup',
        [['ANTHRO',
           [courses['ANTHRO 115'],
            courses['ANTHRO 121C'],
            courses['ANTHRO 127A'],
            courses['ANTHRO 127B'],
            courses['ANTHRO 132A'],
            courses['ANTHRO 135'],
            courses['ANTHRO 169B'],
            courses['ANTHRO C100'],
            courses['ANTHRO C103'],
            courses['ANTHRO C124C'],
            courses['ANTHRO C129D']]],
          ['ARCH',
           [courses['ARCH 140'], courses['ARCH 150'], courses['ARCH 154']]],
          ['ASTRON',
           [courses['ASTRON 128'],
            courses['ASTRON 160'],
            courses['ASTRON C161'],
            courses['ASTRON C162']]],
          ['BIO ENG',
           [courses['BIO ENG 104'],
            courses['BIO ENG 131'],
            courses['BIO ENG 144'],
            courses['BIO ENG 147'],
            courses['BIO ENG C112'],
            courses['BIO ENG C117'],
            courses['BIO ENG C119'],
            courses['BIO ENG C125'],
            courses['BIO ENG C125B'],
            courses['BIO ENG C136L'],
            courses['BIO ENG C137'],
            courses['BIO ENG C145L'],
            courses['BIO ENG C145M'],
            courses['BIO ENG C165'],
            courses['BIO ENG C181']]],
          ['CHEM',
           [courses['CHEM 120A'],
            courses['CHEM 120B'],
            courses['CHEM C110L'],
            courses['CHEM C130'],
            courses['CHEM C138']]],
          ['CHM ENG',
           [courses['CHM ENG 140'],
            courses['CHM ENG 141'],
            courses['CHM ENG C195A']]],
          ['CIV ENG',
           [courses['CIV ENG 100'],
            courses['CIV ENG 103'],
            courses['CIV ENG 155'],
            courses['CIV ENG C106'],
            courses['CIV ENG C116'],
            courses['CIV ENG C133']]],
          ['COG SCI',
           [courses['COG SCI 131'],
            courses['COG SCI C100'],
            courses['COG SCI C101'],
            courses['COG SCI C102'],
            courses['COG SCI C126'],
            courses['COG SCI C127'],
            courses['COG SCI C140']]],
          ['COMPSCI',
           [courses['COMPSCI 152'],
            courses['COMPSCI 160'],
            courses['COMPSCI 161'],
            courses['COMPSCI 162'],
            courses['COMPSCI 164'],
            courses['COMPSCI 168'],
            courses['COMPSCI 169'],
            courses['COMPSCI 170'],
            courses['COMPSCI 172'],
            courses['COMPSCI 176'],
            courses['COMPSCI 182'],
            courses['COMPSCI 184'],
            courses['COMPSCI 186'],
            courses['COMPSCI 188'],
            courses['COMPSCI 189'],
            courses['COMPSCI W186']]],
          ['CY PLAN',
           [courses['CY PLAN 101'],
            courses['CY PLAN 118AC'],
            courses['CY PLAN 119']]],
          ['DEMOG',
           [courses['DEMOG 110'],
            courses['DEMOG 180'],
            courses['DEMOG 260'],
            courses['DEMOG C126'],
            courses['DEMOG C175']]],
          ['ECON',
           [courses['ECON 101A'],
            courses['ECON 101B'],
            courses['ECON 104'],
            courses['ECON 119'],
            courses['ECON 121'],
            courses['ECON 131'],
            courses['ECON 136'],
            courses['ECON 138'],
            courses['ECON 139'],
            courses['ECON 141'],
            courses['ECON 157'],
            courses['ECON 174'],
            courses['ECON 182'],
            courses['ECON C102'],
            courses['ECON C103'],
            courses['ECON C125'],
            courses['ECON C142'],
            courses['ECON C171'],
            courses['ECON C175'],
            courses['ECON C181'],
            courses['ECON N175']]],
          ['EL ENG',
           [courses['EL ENG 105'],
            courses['EL ENG 113'],
            courses['EL ENG 117'],
            courses['EL ENG 118'],
            courses['EL ENG 120'],
            courses['EL ENG 121'],
            courses['EL ENG 122'],
            courses['EL ENG 123'],
            courses['EL ENG 129'],
            courses['EL ENG 130'],
            courses['EL ENG 134'],
            courses['EL ENG 137A'],
            courses['EL ENG 137B'],
            courses['EL ENG 140'],
            courses['EL ENG 142'],
            courses['EL ENG 143'],
            courses['EL ENG 144'],
            courses['EL ENG 147'],
            courses['EL ENG C106A'],
            courses['EL ENG C106B'],
            courses['EL ENG C128'],
            courses['EL ENG C145B'],
            courses['EL ENG C145L'],
            courses['EL ENG C145M'],
            courses['EL ENG C145O']]],
          ['ENE,RES',
           [courses['ENE,RES 102'],
            courses['ENE,RES 131'],
            courses['ENE,RES 175'],
            courses['ENE,RES C100'],
            courses['ENE,RES C176']]],
          ['ENGIN', [courses['ENGIN 117'], courses['ENGIN 120']]],
          ['ENVECON',
           [courses['ENVECON 131'],
            courses['ENVECON 140AC'],
            courses['ENVECON 141'],
            courses['ENVECON 142'],
            courses['ENVECON 143'],
            courses['ENVECON 145'],
            courses['ENVECON 147'],
            courses['ENVECON 152'],
            courses['ENVECON 153'],
            courses['ENVECON 154'],
            courses['ENVECON 161'],
            courses['ENVECON 162'],
            courses['ENVECON C101'],
            courses['ENVECON C102'],
            courses['ENVECON C115'],
            courses['ENVECON C151'],
            courses['ENVECON C175'],
            courses['ENVECON C176'],
            courses['ENVECON C181'],
            courses['ENVECON C183']]],
          ['EPS',
           [courses['EPS 101'],
            courses['EPS 130'],
            courses['EPS C129'],
            courses['EPS C146'],
            courses['EPS C162'],
            courses['EPS C180'],
            courses['EPS C181']]],
          ['ESPM',
           [courses['ESPM 102C'],
            courses['ESPM 102D'],
            courses['ESPM 108A'],
            courses['ESPM 108B'],
            courses['ESPM 111'],
            courses['ESPM 112'],
            courses['ESPM 114'],
            courses['ESPM 115C'],
            courses['ESPM 116B'],
            courses['ESPM 116C'],
            courses['ESPM 117'],
            courses['ESPM 118'],
            courses['ESPM 120'],
            courses['ESPM 121'],
            courses['ESPM 131'],
            courses['ESPM 132'],
            courses['ESPM 140'],
            courses['ESPM 142'],
            courses['ESPM 144'],
            courses['ESPM 152'],
            courses['ESPM 165'],
            courses['ESPM 166'],
            courses['ESPM 172'],
            courses['ESPM 173'],
            courses['ESPM 181A'],
            courses['ESPM 182'],
            courses['ESPM 183'],
            courses['ESPM 185'],
            courses['ESPM 186'],
            courses['ESPM 187'],
            courses['ESPM C103'],
            courses['ESPM C104'],
            courses['ESPM C107'],
            courses['ESPM C126'],
            courses['ESPM C128'],
            courses['ESPM C129'],
            courses['ESPM C138'],
            courses['ESPM C148'],
            courses['ESPM C149'],
            courses['ESPM C159'],
            courses['ESPM C177'],
            courses['ESPM C180'],
            courses['ESPM C183']]],
          ['GEOG',
           [courses['GEOG 140A'],
            courses['GEOG 142'],
            courses['GEOG 143'],
            courses['GEOG 187'],
            courses['GEOG C136'],
            courses['GEOG C139'],
            courses['GEOG C145'],
            courses['GEOG C188']]],
          ['IAS', [courses['IAS C175'], courses['IAS C176']]],
          ['IND ENG',
           [courses['IND ENG 115'],
            courses['IND ENG 130'],
            courses['IND ENG 135'],
            courses['IND ENG 142'],
            courses['IND ENG 150'],
            courses['IND ENG 151'],
            courses['IND ENG 153'],
            courses['IND ENG 160'],
            courses['IND ENG 162'],
            courses['IND ENG 166'],
            courses['IND ENG 170'],
            courses['IND ENG 171'],
            courses['IND ENG 221'],
            courses['IND ENG 222']]],
          ['INFO',
           [courses['INFO 154'],
            courses['INFO 159'],
            courses['INFO 188'],
            courses['INFO 213'],
            courses['INFO 232'],
            courses['INFO 247'],
            courses['INFO 256'],
            courses['INFO 257'],
            courses['INFO 271B'],
            courses['INFO 272']]],
          ['INTEGBI',
           [courses['INTEGBI 102LF'],
            courses['INTEGBI 103LF'],
            courses['INTEGBI 104LF'],
            courses['INTEGBI 106A'],
            courses['INTEGBI 113L'],
            courses['INTEGBI 115'],
            courses['INTEGBI 117'],
            courses['INTEGBI 118'],
            courses['INTEGBI 119'],
            courses['INTEGBI 123AL'],
            courses['INTEGBI 128'],
            courses['INTEGBI 131'],
            courses['INTEGBI 132'],
            courses['INTEGBI 135'],
            courses['INTEGBI 137'],
            courses['INTEGBI 138'],
            courses['INTEGBI 139'],
            courses['INTEGBI 140'],
            courses['INTEGBI 146LF'],
            courses['INTEGBI 148'],
            courses['INTEGBI 151'],
            courses['INTEGBI 152'],
            courses['INTEGBI 153'],
            courses['INTEGBI 154'],
            courses['INTEGBI 157LF'],
            courses['INTEGBI 158LF'],
            courses['INTEGBI 160'],
            courses['INTEGBI 161'],
            courses['INTEGBI 162'],
            courses['INTEGBI 164'],
            courses['INTEGBI 168L'],
            courses['INTEGBI 169'],
            courses['INTEGBI 173LF'],
            courses['INTEGBI 174LF'],
            courses['INTEGBI 175LF'],
            courses['INTEGBI 181L'],
            courses['INTEGBI 183L'],
            courses['INTEGBI 184L'],
            courses['INTEGBI C107L'],
            courses['INTEGBI C109'],
            courses['INTEGBI C110L'],
            courses['INTEGBI C125L'],
            courses['INTEGBI C129L'],
            courses['INTEGBI C135L'],
            courses['INTEGBI C142L'],
            courses['INTEGBI C143A'],
            courses['INTEGBI C143B'],
            courses['INTEGBI C144'],
            courses['INTEGBI C149'],
            courses['INTEGBI C155'],
            courses['INTEGBI C156'],
            courses['INTEGBI C185L'],
            courses['INTEGBI C187']]],
          ['L & S', [courses['L & S C180U']]],
          ['LD ARCH',
           [courses['LD ARCH 122'],
            courses['LD ARCH C177'],
            courses['LD ARCH C188']]],
          ['LEGALST', [courses['LEGALST 123']]],
          ['LINGUIS',
           [courses['LINGUIS 100'],
            courses['LINGUIS 110'],
            courses['LINGUIS 113'],
            courses['LINGUIS 140'],
            courses['LINGUIS C105'],
            courses['LINGUIS C146'],
            courses['LINGUIS C160']]],
          ['MATH',
           [courses['MATH 104'],
            courses['MATH 105'],
            courses['MATH 110'],
            courses['MATH 113'],
            courses['MATH 114'],
            courses['MATH 115'],
            courses['MATH 116'],
            courses['MATH 118'],
            courses['MATH 121A'],
            courses['MATH 121B'],
            courses['MATH 123'],
            courses['MATH 125A'],
            courses['MATH 126'],
            courses['MATH 127'],
            courses['MATH 128A'],
            courses['MATH 128B'],
            courses['MATH 130'],
            courses['MATH 135'],
            courses['MATH 136'],
            courses['MATH 140'],
            courses['MATH 141'],
            courses['MATH 142'],
            courses['MATH 143'],
            courses['MATH 170'],
            courses['MATH 172'],
            courses['MATH 185'],
            courses['MATH 189'],
            courses['MATH 221'],
            courses['MATH C103'],
            courses['MATH H104'],
            courses['MATH H110'],
            courses['MATH H113'],
            courses['MATH H185']]],
          ['MCELLBI',
           [courses['MCELLBI 100B'],
            courses['MCELLBI 102'],
            courses['MCELLBI 104'],
            courses['MCELLBI 110'],
            courses['MCELLBI 130'],
            courses['MCELLBI 132'],
            courses['MCELLBI 133L'],
            courses['MCELLBI 135A'],
            courses['MCELLBI 136'],
            courses['MCELLBI 137L'],
            courses['MCELLBI 140'],
            courses['MCELLBI 140L'],
            courses['MCELLBI 141'],
            courses['MCELLBI 143'],
            courses['MCELLBI 149'],
            courses['MCELLBI 150'],
            courses['MCELLBI 150L'],
            courses['MCELLBI 160'],
            courses['MCELLBI 160L'],
            courses['MCELLBI 161'],
            courses['MCELLBI 163L'],
            courses['MCELLBI 165'],
            courses['MCELLBI 166'],
            courses['MCELLBI C100A'],
            courses['MCELLBI C103'],
            courses['MCELLBI C110L'],
            courses['MCELLBI C112'],
            courses['MCELLBI C114'],
            courses['MCELLBI C116'],
            courses['MCELLBI C134'],
            courses['MCELLBI C148']]],
          ['MEC ENG',
           [courses['MEC ENG 101'],
            courses['MEC ENG 102B'],
            courses['MEC ENG 104'],
            courses['MEC ENG 106'],
            courses['MEC ENG 108'],
            courses['MEC ENG 109'],
            courses['MEC ENG 110'],
            courses['MEC ENG 118'],
            courses['MEC ENG 119'],
            courses['MEC ENG 120'],
            courses['MEC ENG 122'],
            courses['MEC ENG 130'],
            courses['MEC ENG 131'],
            courses['MEC ENG 132'],
            courses['MEC ENG 133'],
            courses['MEC ENG 135'],
            courses['MEC ENG 138'],
            courses['MEC ENG 140'],
            courses['MEC ENG 146'],
            courses['MEC ENG 150A'],
            courses['MEC ENG 151'],
            courses['MEC ENG 163'],
            courses['MEC ENG 164'],
            courses['MEC ENG 165'],
            courses['MEC ENG 167'],
            courses['MEC ENG 168'],
            courses['MEC ENG 170'],
            courses['MEC ENG 173'],
            courses['MEC ENG 175'],
            courses['MEC ENG 185'],
            courses['MEC ENG C115'],
            courses['MEC ENG C117'],
            courses['MEC ENG C134'],
            courses['MEC ENG C176'],
            courses['MEC ENG C178'],
            courses['MEC ENG C180']]],
          ['MUSIC',
           [courses['MUSIC 108'],
            courses['MUSIC 108M'],
            courses['MUSIC 109'],
            courses['MUSIC 109M']]],
          ['NUC ENG',
           [courses['NUC ENG 100'],
            courses['NUC ENG 130'],
            courses['NUC ENG 175']]],
          ['NUSCTX',
           [courses['NUSCTX 103'],
            courses['NUSCTX 110'],
            courses['NUSCTX 121'],
            courses['NUSCTX C114'],
            courses['NUSCTX C159']]],
          ['PB HLTH',
           [courses['PB HLTH 112'],
            courses['PB HLTH 126'],
            courses['PB HLTH 150A'],
            courses['PB HLTH 150B'],
            courses['PB HLTH 162A'],
            courses['PB HLTH 250A'],
            courses['PB HLTH 252B']]],
          ['PHILOS',
           [courses['PHILOS 128'],
            courses['PHILOS 140A'],
            courses['PHILOS 140B'],
            courses['PHILOS 142'],
            courses['PHILOS 143'],
            courses['PHILOS 146']]],
          ['PHYS ED', [courses['PHYS ED C129'], courses['PHYS ED C165']]],
          ['PHYSICS',
           [courses['PHYSICS 105'],
            courses['PHYSICS 110A'],
            courses['PHYSICS 110B'],
            courses['PHYSICS 111A'],
            courses['PHYSICS 111B'],
            courses['PHYSICS 112'],
            courses['PHYSICS 129'],
            courses['PHYSICS 130'],
            courses['PHYSICS 137A'],
            courses['PHYSICS 137B'],
            courses['PHYSICS 138'],
            courses['PHYSICS 139'],
            courses['PHYSICS 141A'],
            courses['PHYSICS 141B'],
            courses['PHYSICS 142'],
            courses['PHYSICS 151'],
            courses['PHYSICS 177'],
            courses['PHYSICS C161']]],
          ['PLANTBI',
           [courses['PLANTBI 101L'],
            courses['PLANTBI 113'],
            courses['PLANTBI 120'],
            courses['PLANTBI 135'],
            courses['PLANTBI 150'],
            courses['PLANTBI 160'],
            courses['PLANTBI 165'],
            courses['PLANTBI 185'],
            courses['PLANTBI 190'],
            courses['PLANTBI C103'],
            courses['PLANTBI C107L'],
            courses['PLANTBI C109'],
            courses['PLANTBI C110L'],
            courses['PLANTBI C112'],
            courses['PLANTBI C114'],
            courses['PLANTBI C116'],
            courses['PLANTBI C124'],
            courses['PLANTBI C134'],
            courses['PLANTBI C148']]],
          ['POL SCI', [courses['POL SCI 133'], courses['POL SCI C131A']]],
          ['PSYCH',
           [courses['PSYCH 110'],
            courses['PSYCH 114'],
            courses['PSYCH 117'],
            courses['PSYCH 121'],
            courses['PSYCH 122'],
            courses['PSYCH 125'],
            courses['PSYCH 130'],
            courses['PSYCH 131'],
            courses['PSYCH 133'],
            courses['PSYCH 140'],
            courses['PSYCH 141'],
            courses['PSYCH 150'],
            courses['PSYCH 164'],
            courses['PSYCH C113'],
            courses['PSYCH C116'],
            courses['PSYCH C120'],
            courses['PSYCH C126'],
            courses['PSYCH C127'],
            courses['PSYCH C129'],
            courses['PSYCH C143']]],
          ['PUB POL',
           [courses['PUB POL 101'],
            courses['PUB POL C103'],
            courses['PUB POL C142'],
            courses['PUB POL C184']]],
          ['RHETOR', [courses['RHETOR 107'], courses['RHETOR 170']]],
          ['SOCIOL',
           [courses['SOCIOL 105'],
            courses['SOCIOL 106'],
            courses['SOCIOL 108']]],
          ['UGBA',
           [courses['UGBA 101A'],
            courses['UGBA 101B'],
            courses['UGBA 102A'],
            courses['UGBA 102B'],
            courses['UGBA 103'],
            courses['UGBA 106'],
            courses['UGBA 118'],
            courses['UGBA 119'],
            courses['UGBA 120AA'],
            courses['UGBA 120AB'],
            courses['UGBA 120B'],
            courses['UGBA 122'],
            courses['UGBA 126'],
            courses['UGBA 131'],
            courses['UGBA 131A'],
            courses['UGBA 132'],
            courses['UGBA 133'],
            courses['UGBA 134'],
            courses['UGBA 136F'],
            courses['UGBA 141'],
            courses['UGBA 160'],
            courses['UGBA 161'],
            courses['UGBA 162'],
            courses['UGBA 165'],
            courses['UGBA 169'],
            courses['UGBA 180'],
            courses['UGBA 183'],
            courses['UGBA 184']]]]]
      }
  ]

  export default Statistics_Major_Requirements