import courses from '../../../../courses.json';
    
    const PolitcalScience_Major_Requirements = [
    {
      "Division": "Lower Division",
      "Requirement": "Into to American Politics",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses["POL SCI 1"], courses["POL SCI N1AC"]]
    },
    { 
      "Division": "Lower Division",
      "Requirement": "Intro to Comparative Politics",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses["POL SCI 2"], courses["POL SCI N2"]]
    },
    {
      "Division": "Lower Division",
      "Requirement": "Intro to Political Theory",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses["POL SCI 4"]]
    },
    {
      "Division": "Lower Division",
      "Requirement": "Intro to International Relations",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses["POL SCI 5"]]
    },
    {
      "Division": "Lower Division",
      "Requirement": "Methods",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses["POL SCI 3"], courses["POL SCI N3"], courses["POL SCI W3"]]
    },
    {
      "Division": "Lower Division",
      "Requirement": "History",
      "Number of Classes": 1,
      "Minimum Units": 3,
      "Course":['departmentsubgroup',
      [['AFRICAM',
         [courses['AFRICAM 111'],
          courses['AFRICAM 4A'],
          courses['AFRICAM 4B'],
          courses['AFRICAM N4A']]],
        ['ASIANST', [courses['ASIANST 10']]],
        ['CELTIC', [courses['CELTIC 70']]],
        ['CLASSIC', [courses['CLASSIC 10A'], courses['CLASSIC 10B']]],
        ['ECON', [courses['ECON 113'], courses['ECON 115']]],
        ['ETH STD', [courses['ETH STD 10AC'], courses['ETH STD 21AC']]],
        ['GEOG', [courses['GEOG C55']]],
        ['GERMAN', [courses['GERMAN 160A'], courses['GERMAN 160C']]],
        ['GLOBAL', [courses['GLOBAL 45']]],
        ['HISTORY',
         [courses['HISTORY 10'],
          courses['HISTORY 105A'],
          courses['HISTORY 105B'],
          courses['HISTORY 106A'],
          courses['HISTORY 106B'],
          courses['HISTORY 108'],
          courses['HISTORY 11'],
          courses['HISTORY 112B'],
          courses['HISTORY 12'],
          courses['HISTORY 122AC'],
          courses['HISTORY 123'],
          courses['HISTORY 124A'],
          courses['HISTORY 124B'],
          courses['HISTORY 130'],
          courses['HISTORY 131B'],
          courses['HISTORY 133A'],
          courses['HISTORY 137AC'],
          courses['HISTORY 14'],
          courses['HISTORY 140B'],
          courses['HISTORY 141B'],
          courses['HISTORY 142'],
          courses['HISTORY 143'],
          courses['HISTORY 149B'],
          courses['HISTORY 150B'],
          courses['HISTORY 151A'],
          courses['HISTORY 151B'],
          courses['HISTORY 151C'],
          courses['HISTORY 152A'],
          courses['HISTORY 155A'],
          courses['HISTORY 155B'],
          courses['HISTORY 158A'],
          courses['HISTORY 158B'],
          courses['HISTORY 158C'],
          courses['HISTORY 159A'],
          courses['HISTORY 159B'],
          courses['HISTORY 160'],
          courses['HISTORY 162A'],
          courses['HISTORY 162B'],
          courses['HISTORY 164A'],
          courses['HISTORY 164B'],
          courses['HISTORY 165A'],
          courses['HISTORY 165B'],
          courses['HISTORY 166B'],
          courses['HISTORY 166C'],
          courses['HISTORY 167A'],
          courses['HISTORY 167B'],
          courses['HISTORY 167C'],
          courses['HISTORY 168A'],
          courses['HISTORY 169A'],
          courses['HISTORY 170'],
          courses['HISTORY 171A'],
          courses['HISTORY 171B'],
          courses['HISTORY 171C'],
          courses['HISTORY 173B'],
          courses['HISTORY 173C'],
          courses['HISTORY 177A'],
          courses['HISTORY 177B'],
          courses['HISTORY 185A'],
          courses['HISTORY 185B'],
          courses['HISTORY 4A'],
          courses['HISTORY 4B'],
          courses['HISTORY 5'],
          courses['HISTORY 6A'],
          courses['HISTORY 6B'],
          courses['HISTORY 7A'],
          courses['HISTORY 7B'],
          courses['HISTORY 8A'],
          courses['HISTORY 8B'],
          courses['HISTORY C139B'],
          courses['HISTORY C139C'],
          courses['HISTORY C139D'],
          courses['HISTORY C157'],
          courses['HISTORY C175B']]],
        ['NE STUD',
         [courses['NE STUD 10'],
          courses['NE STUD 109'],
          courses['NE STUD 130A'],
          courses['NE STUD 130B'],
          courses['NE STUD 147'],
          courses['NE STUD 173A'],
          courses['NE STUD 173B'],
          courses['NE STUD 175'],
          courses['NE STUD C26']]],
        ['PACS', [courses['PACS 125AC']]],
        ['PORTUG', [courses['PORTUG 113']]],
        ['SCANDIN', [courses['SCANDIN 123']]]]]
    },
    {
        "Division": "Lower Division",
        "Requirement": "American Politics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['POL SCI 1'],
        courses['POL SCI N1AC'],
        courses['POL SCI 102'],
        courses['POL SCI 103'],
        courses['POL SCI 103W'],
        courses['POL SCI 104'],
        courses['POL SCI 105'],
        courses['POL SCI 106A'],
        courses['POL SCI 109A'],
        courses['POL SCI 109B'],
        courses['POL SCI 109D'],
        courses['POL SCI 109G'],
        courses['POL SCI 109H'],
        courses['POL SCI 109L'],
        courses['POL SCI 109M'],
        courses['POL SCI 109P'],
        courses['POL SCI 109R'],
        courses['POL SCI 109S'],
        courses['POL SCI 109W'],
        courses['POL SCI 109Z'],
        courses['POL SCI 111AC'],
        courses['POL SCI 150'],
        courses['POL SCI 157A'],
        courses['POL SCI 157B'],
        courses['POL SCI 161'],
        courses['POL SCI 164A'],
        courses['POL SCI 166'],
        courses['POL SCI 167'],
        courses['POL SCI 167AC'],
        courses['POL SCI 169'],
        courses['POL SCI 171'],
        courses['POL SCI 175A'],
        courses['POL SCI 181'],
        courses['POL SCI 186'],
        courses['POL SCI N164A']]
    },
    {
      "Division": "Lower Division",
      "Requirement": "Comparative Politics",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses['POL SCI 2'],
      courses['POL SCI N2'],
      courses['POL SCI 137A'],
      courses['POL SCI 138E'],
      courses['POL SCI 138F'],
      courses['POL SCI 138G'],
      courses['POL SCI 139B'],
      courses['POL SCI 139D'],
      courses['POL SCI 140E'],
      courses['POL SCI 140F'],
      courses['POL SCI 140L'],
      courses['POL SCI 140M'],
      courses['POL SCI 140R'],
      courses['POL SCI 140S'],
      courses['POL SCI 140W'],
      courses['POL SCI 140Z'],
      courses['POL SCI 141C'],
      courses['POL SCI 142A'],
      courses['POL SCI 143A'],
      courses['POL SCI 143B'],
      courses['POL SCI 143C'],
      courses['POL SCI 143T'],
      courses['POL SCI 144'],
      courses['POL SCI 144B'],
      courses['POL SCI 145A'],
      courses['POL SCI 145B'],
      courses['POL SCI 146A'],
      courses['POL SCI 146D'],
      courses['POL SCI 147F'],
      courses['POL SCI 147G'],
      courses['POL SCI 147T'],
      courses['POL SCI 148A'],
      courses['POL SCI 149'],
      courses['POL SCI C139'],
      courses['POL SCI N146C'],
      courses['POL SCI W145A']]
    },{
        "Division": "Lower Division",
        "Requirement": "Emperical Theory and Quantitative Methods",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses['POL SCI 3'],courses['POL SCI N3'],courses['POL SCI W3'],courses['POL SCI C131A'],courses['POL SCI C135'],courses['POL SCI W135']]
        },
    {
    "Division": "Lower Division",
    "Requirement": "Political Theory",
    "Number of Classes": 1,
    "Minimum Units": 4,
    "Course": [courses['POL SCI 4'],courses['POL SCI 111AC'],courses['POL SCI 112A'],courses['POL SCI N112A'],courses['POL SCI 112B'],courses['POL SCI 112C'],courses['POL SCI 112D'],courses['POL SCI N113A'],courses['POL SCI 114A'],courses['POL SCI 116'], courses['POL SCI 117']]
    },
    {
      "Division": "Lower Division",
      "Requirement": "International Relations",
      "Number of Classes": 1,
      "Minimum Units": 4,
      "Course": [courses['POL SCI 5'], courses['POL SCI 122A'], courses['POL SCI 123'], courses['POL SCI 124A'], courses['POL SCI 124C'], courses['POL SCI 124M'], courses['POL SCI 125'], courses['POL SCI 126A'],courses['POL SCI 128'],courses['POL SCI 128A'],courses['POL SCI 138E'], courses['POL SCI 144']]
    },
    {
      "Division": "Upper Division",
      "Requirement": "Subfield Specialization*",
      "Number of Classes": 3,
      "Minimum Units": 12,
      "Notes": "Must complete two upper division courses in one of the following subfields along with the introductory course for the corresponding subgroup (see lower division).",
      "Course": ["departmentsubgroup",
    [['American Politics', [courses['POL SCI 1'],
    courses['POL SCI N1AC'],
    courses['POL SCI 102'],
    courses['POL SCI 103'],
    courses['POL SCI 103W'],
    courses['POL SCI 104'],
    courses['POL SCI 105'],
    courses['POL SCI 106A'],
    courses['POL SCI 109A'],
    courses['POL SCI 109B'],
    courses['POL SCI 109D'],
    courses['POL SCI 109G'],
    courses['POL SCI 109H'],
    courses['POL SCI 109L'],
    courses['POL SCI 109M'],
    courses['POL SCI 109P'],
    courses['POL SCI 109R'],
    courses['POL SCI 109S'],
    courses['POL SCI 109W'],
    courses['POL SCI 109Z'],
    courses['POL SCI 111AC'],
    courses['POL SCI 150'],
    courses['POL SCI 157A'],
    courses['POL SCI 157B'],
    courses['POL SCI 161'],
    courses['POL SCI 164A'],
    courses['POL SCI 166'],
    courses['POL SCI 167'],
    courses['POL SCI 167AC'],
    courses['POL SCI 169'],
    courses['POL SCI 171'],
    courses['POL SCI 175A'],
    courses['POL SCI 181'],
    courses['POL SCI 186'],
    courses['POL SCI N164A']]],
    ['Comparative Politics', [courses['POL SCI 2'],
    courses['POL SCI N2'],
    courses['POL SCI 137A'],
    courses['POL SCI 138E'],
    courses['POL SCI 138F'],
    courses['POL SCI 138G'],
    courses['POL SCI 139B'],
    courses['POL SCI 139D'],
    courses['POL SCI 140E'],
    courses['POL SCI 140F'],
    courses['POL SCI 140L'],
    courses['POL SCI 140M'],
    courses['POL SCI 140R'],
    courses['POL SCI 140S'],
    courses['POL SCI 140W'],
    courses['POL SCI 140Z'],
    courses['POL SCI 141C'],
    courses['POL SCI 142A'],
    courses['POL SCI 143A'],
    courses['POL SCI 143B'],
    courses['POL SCI 143C'],
    courses['POL SCI 143T'],
    courses['POL SCI 144'],
    courses['POL SCI 144B'],
    courses['POL SCI 145A'],
    courses['POL SCI 145B'],
    courses['POL SCI 146A'],
    courses['POL SCI 146D'],
    courses['POL SCI 147F'],
    courses['POL SCI 147G'],
    courses['POL SCI 147T'],
    courses['POL SCI 148A'],
    courses['POL SCI 149'],
    courses['POL SCI C139'],
    courses['POL SCI N146C'],
    courses['POL SCI W145A']]],
    ['Emperical Theory and Quantitative Methods',[[courses['POL SCI 3'],courses['POL SCI N3'],courses['POL SCI W3'],courses['POL SCI C131A'],courses['POL SCI C135'],courses['POL SCI W135']]]],
    ['Political Theory',[courses['POL SCI 4'],courses['POL SCI 111AC'],courses['POL SCI 112A'],courses['POL SCI N112A'],courses['POL SCI 112B'],courses['POL SCI 112C'],courses['POL SCI 112D'],courses['POL SCI N113A'],courses['POL SCI 114A'],courses['POL SCI 116'], courses['POL SCI 117']]],
    ['International Relations',[courses['POL SCI 5'], courses['POL SCI 122A'], courses['POL SCI 123'], courses['POL SCI 124A'], courses['POL SCI 124C'], courses['POL SCI 124M'], courses['POL SCI 125'], courses['POL SCI 126A'],courses['POL SCI 128'],courses['POL SCI 128A'],courses['POL SCI 138E'], courses['POL SCI 144']]]]]
    },
    {
      "Division": "Upper Division",
      "Requirement": "Upper Division Political Science",
      "Number of Classes": 8,
      "Minimum Units": 3,
      "Course": [courses['POL SCI 102'],
      courses['POL SCI 103'],
      courses['POL SCI 103W'],
      courses['POL SCI 104'],
      courses['POL SCI 105'],
      courses['POL SCI 106A'],
      courses['POL SCI 109'],
      courses['POL SCI 110B'],
      courses['POL SCI 111AC'],
      courses['POL SCI 112A'],
      courses['POL SCI 112B'],
      courses['POL SCI 112C'],
      courses['POL SCI 112D'],
      courses['POL SCI N112A'],
      courses['POL SCI N113A'],
      courses['POL SCI 114A'],
      courses['POL SCI 116'],
      courses['POL SCI 117'],
      courses['POL SCI 118AC'],
      courses['POL SCI 122A'],
      courses['POL SCI 123'],
      courses['POL SCI 124A'],
      courses['POL SCI 124B'],
      courses['POL SCI 124C'],
      courses['POL SCI 124M'],
      courses['POL SCI 125'],
      courses['POL SCI 126A'],
      courses['POL SCI 128'],
      courses['POL SCI 128A'],
      courses['POL SCI C131A'],
      courses['POL SCI 133'],
      courses['POL SCI C135'],
      courses['POL SCI W135'],
      courses['POL SCI 137A'],
      courses['POL SCI 138E'],
      courses['POL SCI 138F'],
      courses['POL SCI 138G'],
      courses['POL SCI 139B'],
      courses['POL SCI C139'],
      courses['POL SCI 139D'],
      courses['POL SCI 140E'],
      courses['POL SCI 140F'],
      courses['POL SCI 140L'],
      courses['POL SCI 140M'],
      courses['POL SCI 140R'],
      courses['POL SCI 140S'],
      courses['POL SCI 140W'],
      courses['POL SCI 140Z'],
      courses['POL SCI 141A'],
      courses['POL SCI 141C'],
      courses['POL SCI 142A'],
      courses['POL SCI 143A'],
      courses['POL SCI 143B'],
      courses['POL SCI 143C'],
      courses['POL SCI 143E'],
      courses['POL SCI 143T'],
      courses['POL SCI 144'],
      courses['POL SCI 144B'],
      courses['POL SCI 145A'],
      courses['POL SCI 145B'],
      courses['POL SCI W145A'],
      courses['POL SCI 146A'],
      courses['POL SCI 146D'],
      courses['POL SCI N146C'],
      courses['POL SCI 147F'],
      courses['POL SCI 147G'],
      courses['POL SCI 147T'],
      courses['POL SCI 148A'],
      courses['POL SCI 149'],
      courses['POL SCI 149B'],
      courses['POL SCI 149E'],
      courses['POL SCI 149F'],
      courses['POL SCI 149I'],
      courses['POL SCI 149K'],
      courses['POL SCI 149M'],
      courses['POL SCI 149N'],
      courses['POL SCI 149P'],
      courses['POL SCI 149R'],
      courses['POL SCI 149S'],
      courses['POL SCI 149W'],
      courses['POL SCI 150'],
      courses['POL SCI 152A'],
      courses['POL SCI 157A'],
      courses['POL SCI 157B'],
      courses['POL SCI 161'],
      courses['POL SCI 164A'],
      courses['POL SCI N164A'],
      courses['POL SCI 166'],
      courses['POL SCI 167'],
      courses['POL SCI 167AC'],
      courses['POL SCI 169'],
      courses['POL SCI 171'],
      courses['POL SCI 173S'],
      courses['POL SCI 175A'],
      courses['POL SCI 179'],
      courses['POL SCI 181'],
      courses['POL SCI 182AC'],
      courses['POL SCI 186'],
      courses['POL SCI H190A'],
      courses['POL SCI H190B'],
      courses['POL SCI 191'],
      courses['POL SCI 196'],
      courses['POL SCI C196A'],
      courses['POL SCI C196B'],
      courses['POL SCI C196W'],
      courses['POL SCI 196S'],
      courses['POL SCI 196W'],
      courses['POL SCI 197'],
      courses['POL SCI 198'],
      courses['POL SCI 199']]
    }
  ]

export default PoliticalScience_Major_Requirements;