var majorOptions = [{'value': ['College of Letters and Sciences', 'Data Science'],
'label': 'Data Science'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Biochemistry and Molecular Biology (Track 1)'],
'label': 'Molecular and Cell Biology--Biochemistry and Molecular Biology (Track 1)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Biochemistry and Molecular Biology (Track 2)'],
'label': 'Molecular and Cell Biology--Biochemistry and Molecular Biology (Track 2)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Cell and Developmental Biology (Track 1)'],
'label': 'Molecular and Cell Biology--Cell and Developmental Biology (Track 1)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Cell and Developmental Biology (Track 2)'],
'label': 'Molecular and Cell Biology--Cell and Developmental Biology (Track 2)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Genetics, Genomics and Development (Track 1)'],
'label': 'Molecular and Cell Biology--Genetics, Genomics and Development (Track 1)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Genetics, Genomics and Development (Track 2)'],
'label': 'Molecular and Cell Biology--Genetics, Genomics and Development (Track 2)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Immunology and Pathogenesis (Track 1)'],
'label': 'Molecular and Cell Biology--Immunology and Pathogenesis (Track 1)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Immunology and Pathogenesis (Track 2)'],
'label': 'Molecular and Cell Biology--Immunology and Pathogenesis (Track 2)'},
{'value': ['College of Letters and Sciences',
 'Molecular and Cell Biology--Neurobiology'],
'label': 'Molecular and Cell Biology--Neurobiology'},
{'value': ['College of Letters and Sciences', 'Physics'], 'label': 'Physics'},
{'value': ['College of Letters and Sciences', 'Political Science'],
'label': 'Political Science'},
{'value': ['College of Letters and Sciences', 'Psychology'],
'label': 'Psychology'},
{'value': ['College of Letters and Sciences', 'Statistics'],
'label': 'Statistics'}]

export default majorOptions