import courses from '../../../../courses.json';
    
    const Economics_Major_Requirements = [
    {
      "Division": "Lower Division",
      "Requirement": "Calculus",
      "Number of Classes": 2,
      "Minimum Units": 8,
      "Course": [[courses["MATH 1A"], courses['MATH 1B']], [courses["MATH 16A"], courses['MATH 16B']]]
    },
    {
        "Division": "Lower Division",
        "Requirement": "Statistics",
        "Number of Classes": 1,
        "Minimum Units": 3,
        "Course": [courses['STAT 20'], [courses['STAT 21'], courses['STAT W21'], courses['STAT 88'], courses['STAT 131A'], courses['STAT 135'], courses['STAT 140']]]
    },
    {
        "Division": "Lower Division",
        "Requirement": "Introduction to Economics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses["ECON 1"], [courses['ECON 2']]]
    },
    {
        "Division": "Upper Division",
        "Requirement": "Intermediate Microeconomics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses["ECON 100A"], courses["ECON 101A"]]
    },
    {
        "Division": "Upper Division",
        "Requirement": "Intermediate Macroeconomics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses["ECON 100B"], courses["ECON 101B"], courses['UGBA 101B']]
    },
    {
        "Division": "Upper Division",
        "Requirement": "Econometrics",
        "Number of Classes": 1,
        "Minimum Units": 4,
        "Course": [courses["ECON 140"], courses['ECON 141']]
    },
    {
        "Division": "Upper Division",
        "Requirement": "Electives",
        "Number of Classes": 5,
        "Minimum Units": 15,
        "Course": ['departmentsubgroup',
        [['ECON', [courses['ECON C102'],
        courses['ECON C103'],
        courses['ECON 104'],
        courses['ECON 105'],
        courses['ECON C110'],
        courses['ECON N110'],
        courses['ECON 113'],
        courses['ECON N113'],
        courses['ECON 115'],
        courses['ECON 119'],
        courses['ECON 121'],
        courses['ECON 122'],
        courses['ECON 123'],
        courses['ECON 124'],
        courses['ECON C125'],
        courses['ECON 131'],
        courses['ECON 132'],
        courses['ECON 133'],
        courses['ECON 134'],
        courses['ECON 135'],
        courses['ECON 136'],
        courses['ECON N136'],
        courses['ECON 137'],
        courses['ECON 138'],
        courses['ECON 139'],
        courses['ECON C142'],
        courses['ECON N142'],
        courses['ECON 151'],
        courses['ECON 152'],
        courses['ECON N152'],
        courses['ECON 153'],
        courses['ECON 154'],
        courses['ECON 155'],
        courses['ECON 155A'],
        courses['ECON 157'],
        courses['ECON 161'],
        courses['ECON 162'],
        courses['ECON C171'],
        courses['ECON N171'],
        courses['ECON 172'],
        courses['ECON 173'],
        courses['ECON 174'],
        courses['ECON C175'],
        courses['ECON N175'],
        courses['ECON C181'],
        courses['ECON N181'],
        courses['ECON 182'],
        courses['ECON 191'],
        courses['ECON 196']]],
        ['CY PLAN', [courses['CY PLAN 113A'], courses['CY PLAN 113B']]],
         ['ENGIN', [courses['ENGIN 120']]],
         ['ENVECON',
          [courses['ENVECON 131'],
           courses['ENVECON 141'],
           courses['ENVECON 143'],
           courses['ENVECON 145'],
           courses['ENVECON 152'],
           courses['ENVECON 162'],
           courses['ENVECON C176']]],
         ['HISTORY',
          [courses['HISTORY 133A'],
           courses['HISTORY 159A'],
           courses['HISTORY 159B'],
           courses['HISTORY 160']]],
         ['LEGALST', [courses['LEGALST 145'], courses['LEGALST 147']]],
         ['PHILOS', [courses['PHILOS 141']]],
         ['UGBA',
          [courses['UGBA 118'],
           courses['UGBA 131'],
           courses['UGBA 132'],
           courses['UGBA 133'],
           courses['UGBA 136F'],
           courses['UGBA 180']]]]]
    }
    
  ]
  
export default Economics_Major_Requirements;